purpleclay/nsv

cmd/format.go, cmd/root.go, go.mod, go.sum, internal/nsv/semver.go, internal/nsv/semver_test.go, internal/nsv/tui.go
=> feat: support customisation of the internal version template

internal/nsv/conventional_test.go, internal/nsv/semver.go, internal/nsv/semver_test.go, internal/nsv/tui.go
=> feat: extend the tui to include additional details about the next tag

Taskfile.yml, internal/nsv/conventional_test.go
=> ci: support the running of parallel tests within the workflow

.goreleaser.yml, README.md, cmd/format.go, cmd/next.go
=> feat: expose existing functionality behind a next command

.github/ISSUE_TEMPLATE/ci.yml, .golangci.yml, internal/nsv/conventional_test.go, internal/nsv/semver.go
=> ci: improve usage of golangci-lint by revising existing parser list

cmd/format.go, cmd/next.go, internal/nsv/semver.go, internal/nsv/template.go, internal/nsv/template_test.go
=> feat: verify custom template before calculating the next version

.golangci.yml, Dockerfile, Taskfile.yml, cmd/root.go, cmd/tag.go, htmltest.yml, mkdocs.yml
=> feat: add support to tag a repository with the next semantic version

cmd/next.go, cmd/tag.go, internal/nsv/semver.go
=> feat: add an option to create an annotated tag

Dockerfile, cmd/tag.go, internal/nsv/semver.go
=> feat: support GPG signing of tags

.github/workflows/shellcheck.yml, cmd/tag.go, docs/install/binary.md, scripts/entrypoint.sh, scripts/install
=> feat: include entrypoint script within docker container and bundle gpg-import

.github/workflows/docs.yml, cmd/playground.go, cmd/tag.go, docs/commands.md, docs/install/binary.md, docs/next-version.md, docs/playground.md, docs/reference/cli/nsv-next.md, docs/reference/cli/nsv-playground.md, docs/reference/cli/nsv-tag.md, docs/reference/cli/nsv.md, docs/reference/env-vars.md, docs/reference/templating.md, docs/tag-version.md, mkdocs.yml
=> docs: write documentation for release v0.2.0

.github/workflows/release.yml, .goreleaser.yml
=> ci: update goreleaser config to include missing docker manifests

.github/workflows/ci.yml, .goreleaser.yml
=> ci: build and publish a windows binary

cmd/tag.go
=> feat: print tag to stdout after tagging repository

README.md, docs/github-action.md, docs/gitlab-template.md, docs/index.md, mkdocs.yml
=> docs: include references to github action and gitlab template

cmd/next.go, cmd/next_test.go, cmd/playground.go, cmd/root.go, cmd/tag.go, cmd/tag_test.go, internal/nsv/semver.go, internal/nsv/semver_test.go, internal/nsv/tui.go
=> feat: allow nsv to impersonate a user

.golangci.yml, cmd/next.go, cmd/playground.go, cmd/tag.go, cmd/tag_test.go, internal/nsv/command.go, internal/nsv/command_test.go, internal/nsv/conventional.go, internal/nsv/conventional_test.go, internal/nsv/semver.go, internal/nsv/semver_test.go, internal/nsv/tui.go
=> feat(tui): ensure summary clearly illustrates how increment was determined

internal/nsv/semver.go
=> fix: incorrect log path resolution when executing nsv from within a subdirectory

docs/github-action.md, docs/gitlab-template.md, docs/next-version.md, docs/tag-version.md
=> docs: write documentation for release 0.4.0

cmd/next.go, cmd/tag.go, internal/nsv/semver.go, internal/nsv/semver_test.go, main.go
=> feat: allow a relative path to be provided to nsv when resolving the semantic version

cmd/next.go, cmd/playground.go, cmd/root.go, cmd/tag.go, go.mod, go.sum, internal/nsv/semver.go, internal/nsv/tui.go
=> feat: support a pretty mode for outputting the table in different formats

cmd/next.go, cmd/root.go, cmd/tag.go, cmd/template.go
=> feat: use a custom usage template with cobra for improved formatting

internal/nsv/semver.go, internal/nsv/semver_test.go
=> fix: summary truncates the log directory in its output

cmd/tag.go, cmd/tag_test.go, internal/tui/summary_test.go
=> feat: support go templated strings for custom tag message

docs/github-action.md, docs/monorepos.md, docs/next-version.md, docs/pretty.md, docs/reference/cli/nsv-next.md, docs/reference/cli/nsv-tag.md, docs/reference/env-vars.md, docs/reference/templating.md, docs/tag-version.md, mkdocs.yml
=> docs: write documentation for release 0.5.0

docs/commands.md, docs/docker/running.md, docs/github-action.md, docs/gitlab-template.md, docs/index.md, docs/install/binary.md, docs/install/source.md, docs/license.md, docs/monorepos.md, docs/next-version.md, docs/playground.md, docs/pretty.md, docs/reference/cli/nsv-next.md, docs/reference/cli/nsv-playground.md, docs/reference/cli/nsv-tag.md, docs/reference/cli/nsv.md, docs/reference/env-vars.md, docs/reference/templating.md, docs/tag-version.md
=> docs: enhance social cards with descriptions

.gitignore, go.mod, go.sum, internal/nsv/detect.go, internal/nsv/semver.go
=> feat: auto-detect semantic prefix for initial version based on detected programming language

internal/nsv/detect.go, internal/nsv/semver.go, internal/nsv/semver_test.go, internal/nsv/template.go
=> feat: remove inbuilt sanitisation checks applied to a tag generated by a custom format

Taskfile.yml, go.mod, go.sum, internal/nsv/command.go, internal/nsv/command_test.go
=> feat: support the inclusion of multiple nsv commands

internal/nsv/command.go, internal/nsv/command_test.go, internal/nsv/semver.go, internal/nsv/semver_test.go
=> feat: allow prerelease label to be specified with pre command

go.mod, go.sum, internal/nsv/command.go, internal/nsv/semver.go, internal/nsv/semver_test.go
=> feat: protect against invalid creation of prerelease tags

flake.lock, flake.nix, go.mod, go.sum
=> fix: incorrect formatting of commits with mixed line endings

Dockerfile, scripts/entrypoint.sh
=> fix: failing to import a gpg key should prevent nsv from running

.github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/docs.yml, .github/workflows/nsv.yml, .github/workflows/release.yml, .github/workflows/shellcheck.yml, .goreleaser.yaml, README.md, Taskfile.yaml, docs/ci/dagger.md, docs/ci/github-action.md, docs/ci/gitlab-template.md, docs/commands.md, docs/configurable-prefixes.md, docs/docker/dagger.md, docs/docker/running.md, docs/index.md, docs/overrides/main.html, docs/reference/cli/nsv-next.md, docs/reference/cli/nsv-tag.md, docs/reference/cli/nsv.md, docs/reference/env-vars.md, docs/reference/templating.md, docs/stylesheets/extra.css, mkdocs.yml
=> docs: write documentation for upcoming v0.8.0 release

cmd/root.go, cmd/tag.go, cmd/tag_test.go
=> feat!: allow the commit message to be configurable

cmd/tag.go, internal/nsv/semver.go
=> feat: include working directory within hook environment variables

README.md, cmd/playground.go, docs/ci/dagger.md, docs/configurable-prefixes.md, docs/docker/dagger.md, docs/hooks.md, docs/index.md, docs/reference/cli/nsv-next.md, docs/reference/cli/nsv-tag.md, docs/reference/env-vars.md, docs/reference/templating.md, docs/tag-version.md, mkdocs.yml
=> docs: include documentation on the new hook support

cmd/patch.go, cmd/patch_test.go, cmd/root.go, cmd/tag.go, cmd/tag_test.go
=> feat: add a dedicated patch subcommand for patching and committing file changes

cmd/patch.go, docs/docker/dagger.md, docs/git-signing.md, docs/hooks.md, docs/patch-files.md, docs/reference/cli/nsv-patch.md, docs/reference/env-vars.md, docs/reference/templating.md, docs/tag-version.md, mkdocs.yml
=> docs: extend documentation to include new patch sub-command

cmd/root.go
=> fix: nsv logger issue causes installation to fail (#180)

.goreleaser.yaml
=> ci: extend goreleaser configuration to publish to nix nur

.github/workflows/nsv.yml, .github/workflows/shellcheck.yml, cmd/next.go, cmd/patch.go, cmd/root.go, cmd/tag.go, docs/git-repair.md, go.mod, go.sum, internal/nsv/repository.go, internal/nsv/repository_test.go, internal/nsv/semver.go, mkdocs.yml
=> fix: add support for detecting and repairing a shallow clone of a repository

docs/git-repair.md, docs/install/binary.md, docs/options.md, docs/patch-files.md, docs/reference/cli/nsv-next.md, docs/reference/cli/nsv-patch.md, docs/reference/cli/nsv-tag.md, docs/reference/cli/nsv.md, docs/reference/env-vars.md, docs/running/dagger.md, docs/running/nix.md, mkdocs.yml, taskfile.yaml
=> docs: add a section to the documentation about setting options

docs/install/binary.md
hey. i packaged nsv for Arch :)
=> docs(README): add Arch Linux installation instructions

cmd/patch.go, cmd/patch_test.go
=> fix: a patched commit should skip by default

docs/patch-files.md, docs/reference/cli/nsv-patch.md
=> docs: the default commit when patching files will now skip any subsequent build

cmd/next.go, cmd/patch.go, cmd/tag.go, internal/nsv/repository.go, internal/nsv/semver.go
=> feat: improve the overall verbosity of logging

docs/next-version.md
=> docs: remove any references to the nsv playground as this is temporarily disabled
